// login
export const SUBMIT_LOGIN = 'SUBMIT_LOGIN'
export const RECEIVE_LOGIN_SUCCESS = 'RECEIVE_LOGIN_SUCCESS'
export const RECEIVE_LOGIN_FAILURE = 'RECEIVE_LOGIN_FAILURE'

// registration
export const SUBMIT_REGISTRATION = 'SUBMIT_REGISTRATION'
export const RECEIVE_REGISTRATION_SUCCESS = 'RECEIVE_REGISTRATION_SUCCESS'
export const RECEIVE_REGISTRATION_FAILURE = 'RECEIVE_REGISTRATION_FAILURE'

// password recovery
export const SUBMIT_PASSWORD_RECOVERY = 'SUBMIT_PASSWORD_RECOVERY'
export const RECEIVE_PASSWORD_RECOVERY_SUCCESS = 'RECEIVE_PASSWORD_RECOVERY_SUCCESS'
export const RECEIVE_PASSWORD_RECOVERY_FAILURE = 'RECEIVE_PASSWORD_RECOVERY_FAILURE'